### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by mrmoss** [adv4000/mossadchallenge2019#1]
So I go searching to see if some of the text I'm finding in a binary blob is something that exists, and I find some person doing the same CTF I'm on.

If you take a look at the assets/flutter_assets/kernel_blob.bin file, there's some good code to reverse this challenge.
[code.txt](https://github.com/adv4000/mossadchallenge2019/files/3159960/code.txt)

**Comment by adv4000** [comment]
לפי דעתי סיכוי להתקבל למוסד ע"י פתירה של חידה שועף לאפס למי שבא מבחוץ למשרד ביטחון, אני חושב שרק יוצעי יחידות מחשוב המובחרות  של צה"ל יכולים להתקבל. אבל תמיד מעניין לנסות את הידע שלך...
זה סוג של חידות שתצתרכו לפתור תוך כדי תהליך גיוס.
ותמיד ניתן להגיש קורות חיים ישירות בלי שום  חידות : https://www.mossad.gov.il/heb/careers/Pages/default.aspx
