### ISSUE TITLE
Dont show the solution until the CTF is down

### ISSUE THREAD

**Issue by KoolimRezah** [adv4000/mossadchallenge2019#2]
The CTF is still up and if people search for things related to the CTF you answer pops up first. This ruins the CTF for other people. Maybe keep it private?

**Comment by adv4000** [comment]
Citatel Cyber Security Solutions published full resolution for Mossad Challenge 2018 after only 4 days on many news websites.

**Comment by adv4000** [comment]
לפי דעתי סיכוי להתקבל למוסד ע"י פתירה של חידה שועף לאפס למי שבא מבחוץ למשרד ביטחון, אני חושב שרק יוצעי יחידות מחשוב המובחרות  של צה"ל יכולים להתקבל. אבל תמיד מעניין לנסות את הידע שלך...
זה סוג של חידות שתצתרכו לפתור תוך כדי תהליך גיוס.
ותמיד ניתן להגיש קורות חיים ישירות בלי שום  חידות : https://www.mossad.gov.il/heb/careers/Pages/default.aspx
