### ISSUE TITLE
Private Repo?

### ISSUE THREAD

**Issue by Dviros** [adv4000/mossadchallenge2019#3]
Hi,
Think you should make this private....a lot of n00bs are using other people methods.
Document everything you do, and make it public when the CTF is down (done the same over here: https://github.com/Dviros/Mossad_Challenges)

**Comment by adv4000** [comment]
After few hours since CTF start one guy published link to Challenge2 on Facebook
https://www.facebook.com/pages/Mossad/108612182497342

**Comment by adv4000** [comment]
לפי דעתי סיכוי להתקבל למוסד ע"י פתירה של חידה שועף לאפס למי שבא מבחוץ למשרד ביטחון, אני חושב שרק יוצעי יחידות מחשוב המובחרות  של צה"ל יכולים להתקבל. אבל תמיד מעניין לנסות את הידע שלך...
זה סוג של חידות שתצתרכו לפתור תוך כדי תהליך גיוס.
ותמיד ניתן להגיש קורות חיים ישירות בלי שום  חידות : https://www.mossad.gov.il/heb/careers/Pages/default.aspx
