### ISSUE TITLE
Please Make this repo private until the CTF ends!

### ISSUE THREAD

**Issue by realgam3** [adv4000/mossadchallenge2019#4]
Please Make this repo private until the CTF ends!
Do not share the answers of the Mossad recruit CTF.... 

When the CTF end you will be able to make it public again....

**Comment by adv4000** [comment]
Citatel Cyber Security Solutions published full resolution for Mossad Challenge 2018 after only 4 days on many news websites.
לפי דעתי סיכוי להתקבל למוסד ע"י פתירה של חידה שועף לאפס למי שבא מבחוץ למשרד ביטחון, אני חושב שרק יוצעי יחידות מחשוב המובחרות של צה"ל יכולים להתקבל. אבל תמיד מעניין לנסות את הידע שלך...
זה סוג של חידות שתצתרכו לפתור תוך כדי תהליך גיוס.
ותמיד ניתן להגיש קורות חיים ישירות בלי שום חידות : https://www.mossad.gov.il/heb/careers/Pages/default.aspx

**Comment by adv4000** [comment]
It's already over.
